language: java

jdk:
  - oraclejdk8

script:
  - mvn clean install

after_success:
  - wget http://roboconf.net/resources/build/settings.xml
  - mvn clean deploy -q --settings settings.xml

after_success:
  - ./after_success.sh

notifications:
  email:
  - herve.tchepannou@gmail.com
